import type { RewardData } from "~~/types/reward";

export const sampleRewards: RewardData[] = [
  {
    id: "bk-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Burguer King",
    subtitle: "King",
    address: "106 Liberty St, New York, NY",
    message: "Congrats! Redeem your reward",
    rewardAmount: 15,
    completedSteps: 6,
    totalSteps: 6,
    consumptionNote: "for consumption in the store",
  },
  {
    id: "bk-2",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Burguer King",
    subtitle: "King",
    address: "233 Broadway, New York, NY",
    message: "Congrats! Redeem your reward",
    rewardAmount: 10,
    completedSteps: 4,
    totalSteps: 6,
    consumptionNote: "for consumption in the store",
  },
  {
    id: "mc-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "McDonald's",
    subtitle: "",
    address: "556 7th Ave, New York, NY",
    message: "Almost there! Keep collecting",
    rewardAmount: 5,
    completedSteps: 3,
    totalSteps: 6,
    consumptionNote: "valid for any purchase",
  },
  {
    id: "sb-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Starbucks",
    subtitle: "Coffee",
    address: "1372 Broadway, New York, NY",
    message: "Free coffee waiting for you!",
    rewardAmount: 8,
    completedSteps: 6,
    totalSteps: 6,
    consumptionNote: "valid for any drink",
  },
  {
    id: "kfc-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "KFC",
    subtitle: "",
    address: "220 W 42nd St, New York, NY",
    message: "You're halfway there!",
    rewardAmount: 12,
    completedSteps: 3,
    totalSteps: 6,
    consumptionNote: "for any combo meal",
  },
  {
    id: "taco-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Taco Bell",
    subtitle: "",
    address: "18 E 14th St, New York, NY",
    message: "Congrats! Redeem your reward",
    rewardAmount: 7,
    completedSteps: 6,
    totalSteps: 6,
    consumptionNote: "for any menu item",
  },
  {
    id: "pizza-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Pizza Hut",
    subtitle: "",
    address: "1201 Broadway, New York, NY",
    message: "Almost there!",
    rewardAmount: 20,
    completedSteps: 5,
    totalSteps: 6,
    consumptionNote: "for any large pizza",
  },
  {
    id: "subway-1",
    logoSrc: "/placeholder.svg?height=40&width=40",
    name: "Subway",
    subtitle: "",
    address: "177 E 87th St, New York, NY",
    message: "Free sub sandwich waiting!",
    rewardAmount: 9,
    completedSteps: 6,
    totalSteps: 6,
    consumptionNote: "for any footlong",
  },
]
